### ISSUE TITLE
parse dates to obp format

### ISSUE THREAD

**Issue by chrisjsimpson** [chrisjsimpson/ofx2obp#2]
Currently we don't import the transaction dates correctly

- convert the dates into the date format used by obp

## Current state
We currently hardcode the date: https://github.com/chrisjsimpson/ofx2obp/blob/master/scratch.py#L126
## Desired state
Take the date from the transaction object, and parse the date into obp style date format

**Comment by hongwei1** [comment]
Here is the obp date-time format: 

https://github.com/hongwei1/OBP-API/blob/029f910945b7e554a6e9c761e0350ffdf25c892e/obp-api/src/main/scala/code/api/sandbox/example_data/2016-04-28/example_import.json#L116


Please check here, in API_Manager we try the format stuff before:
https://github.com/OpenBankProject/API-Manager/blob/739c44da62b1474de5e7e245df240114e8291e72/apimanager/apimanager/settings.py#L199-L198

**Comment by chrisjsimpson** [comment]
Thanks @hongwei1. That format might have a name It looks familiar :thinking: 

```
'%Y-%m-%dT%H:%M:%S.%fZ' 
```
cheers

**Comment by chrisjsimpson** [comment]
lines 16-62 is dead code, it was just for placeholder helpful to see a valid payload. https://github.com/chrisjsimpson/ofx2obp/blob/9a345405d21b815a950b006e18209ca7c3df6db7/scratch.py#L16-62

**Comment by chrisjsimpson** [comment]
Thanks @PengfeiLi0218 
https://github.com/chrisjsimpson/ofx2obp/commit/f1036b4161ee9735a480a61f3706dd52d649dfda
